# Artificial Intelligence - Fall 2024 - Laboratory 02:Python Introduction part II


##### Review

The following formula computes a _Z score_ and measures how far a single raw data value is from the population mean.

\begin{equation*}
z = \frac{X - \mu }{\sigma }
\end{equation*}

where:
* **_X_** is a single raw data value
* `mu` is the population mean
* `sigma` is the population standard deviation

To find the standard deviation, the equation below comes in hand:

\begin{equation*}
\sigma = \sqrt{\frac{\sum \left | X - \mu \right |^{2}}{N}}
\end{equation*}

where **_N_** is the number of data points in the population.

**a.** Using `sum()` and `list comprehension`, compute the mean and the standard deviation for the population defined below:

In [81]:
data =  [4.5, 5, 5.5, 6, 6.25, 7, 15.25, 18, 18.45, 21, 21.45, 23]
print(data)

[4.5, 5, 5.5, 6, 6.25, 7, 15.25, 18, 18.45, 21, 21.45, 23]


In [82]:
# Your implementation here:
mean = sum(data) / len(data)
std = (sum([(x - mean) ** 2 for x in data]) / len(data)) ** 0.5
print(mean)
print(std)


12.616666666666667
7.167441818544622


**b.** Define the `z_score()` function and implement the mathematical expression. The obtained values should be stored in a _z score_ values list and rounded to 3 decimals.

In [83]:
# Your implementatio here:
def z_score():
    z = [round((x - mean) / std, 3) for x in data]
    return z

print(z_score())

[-1.132, -1.063, -0.993, -0.923, -0.888, -0.784, 0.367, 0.751, 0.814, 1.17, 1.232, 1.449]


**c.** Add the corresponding elongation of each raw data value into a dictionary.

In [84]:
# Your implementatio here:



## Classes

The object-oriented programming paradigm in Python helps with structuring programs into `individual objects`. But how?

* An Object **O** from a class **C** has a set of properties **_p_** and actions **_a_**.

* The functions of a class are called `methods`. Their responsibility is to model the data corresponding to a given object.

* The objects of a class are known as `instances` and represent the source of collecting data.

```python

class EmptyClas:
    """
    This is a class without variables and methods
    """
    pass # The keyword pass is a placeholder


class MyClass:
    # A class variable
    name = 'My Class'
    
    def my_method(self, my_var):
        # An instance variable
        self.my_instance = my_var
```

In [85]:
# Implement Task 0 b and c here:

class ScientificConference:
    """
    To define the properties of a class, 
    we use a special method called __init__.
    
    The special variable called "self"
    helps with associating the attributes
    w\ the new object: similar to `this`
    keyword from other programming languages
    and required to address variables from
    classes. 
    """
    def __init__(self, name, year, papers=None):
        """
        Establish the attributes of the
        class and assign values to the 
        corresponding parameters.
        """ 
        self.name = name
        self.year = year

        """
        b. Add new attribute `papers`
        """

        if papers is None:
            self.papers = {}
        else:
            self.papers = papers
        
        """
        Remove Duplicates from papers
        """
        
        for author, papers in self.papers.items():
            self.papers[author] = list(set(papers))

        

       

    """Create a new attribute for the `class ScientificConference`, 
    which is a dictionary passed as a parameter to the instances of 
    the class and holds all of the papers of the conference.
    _Note:_ You should check if `papers` is `None` in `__init__` 
    and set it to `{}` instead.
    _Please handle duplicate entries by removing them!_"""

    def add_manuscript(self, title, researcher):
        """
        Add a new manuscript to the papers dictionary.
        """
        if researcher in self.papers:
            if title not in self.papers[researcher]:
                self.papers[researcher].append(title)
        else:
            self.papers[researcher] = [title]

    def __str__(self):
        """
        To return the String representation of
        an object, we use the __str__ method. 
        """
        result = self.name + ' ' + str(self.year) + ': \n'
        for author, papers in self.papers.items():
            result += f'{author}: {", ".join([str(paper) for paper in papers])} \n'
        return result


### Task 0

**a.** Define two new `instances` of the `class ScientificConference` and return their representations.

Your output should look like:

`Proposals for ICML and NeurIPS conferences will be accepted until the end of November 2021.`

_Hint:_ `instance.attribute` helps you extracting a certain property.

In [86]:
# Your implementation here

a = ScientificConference('ICML', 2021)
b = ScientificConference('NeurIPS', 2021)

print("Proposals for", a.name, "and", b.name, "conferences will be accepted until the end of November", str(a.year) + ".")

Proposals for ICML and NeurIPS conferences will be accepted until the end of November 2021.


**b.** Create a new attribute for the `class ScientificConference`, which is a dictionary passed as a parameter to the instances of the class and holds all of the papers of the conference.

_Note:_ You should check if `papers` is `None` in `__init__` and set it to `{}` instead.

_Please handle duplicate entries by removing them!_

In [87]:
# Verifying that dictionary works and duplicates are removed

a = ScientificConference('ICML', 2021, {'John Doe': ['Paper 1', 'Paper 5', 'Paper 2', 'Paper 2'], 'Jane Doe': ['Paper 3']})
print(a)
print(a.papers)

ICML 2021: 
John Doe: Paper 5, Paper 2, Paper 1 
Jane Doe: Paper 3 

{'John Doe': ['Paper 5', 'Paper 2', 'Paper 1'], 'Jane Doe': ['Paper 3']}


**c.** Define the `add_manuscript` method which generates new entries in the dictionary described before. Please consider using the _researcher_ as a `key` and the _title_ as `values`.

In [88]:
# Verify here if your add_manuscript method works: add an item & print it

a.add_manuscript('Paper 4', 'Jane Doe')
print(a)

ICML 2021: 
John Doe: Paper 5, Paper 2, Paper 1 
Jane Doe: Paper 3, Paper 4 



### Task 1

**a.** Define the class `Person` which stores the `title`, `name` and `surname` of a person.

The _tuple_ `allowed_titles` is a class variable which helps to verify if the title of a person is "Mr", "Mrs", "Ms", "Senior Researcher", "Professor of CS" or "Computer Scientist".

An error is returned if the title is not valid.

Use `__str__` defined below:

```python
    def __str__(self):
        return self.title + ' ' + self.surname + ' ' + self.name
```

In [89]:
# Your implementation here
class Person:
    def __init__(self, title, name, surname):
        allowed_titles = ['Mr', 'Mrs', 'Ms', 'Senior Researcher', 'Professor of CS', "Computer Scientist"]

        self.name = name
        self.surname = surname
        if title not in allowed_titles:
            raise ValueError("Title is not right, please choose from the following: 'Mr', 'Mrs', 'Ms', 'Senior Researcher', 'Professor of CS', 'Computer Scientist'")
        else:
            self.title = title

    def __str__(self):
        return self.title + ' ' + self.name + ' ' + self.surname

**b.** Create two instances of the class Person and verify if the following entries are valid:

* _Mr Ian Goodfellow_,
* _SeniorResearcher Tomas Mikolov._

In [90]:
# Your implementation here

Test1 = Person('Mr', 'Ian', 'Goodfellow')
print(Test1)
Test2 = Person('Senior Researcher', 'Tomas', 'Mikolov')
print(Test2)

Mr Ian Goodfellow
Senior Researcher Tomas Mikolov


### Task 2

In `ScientificConference` we have been using the paper parameter as a string, but this concept requires a detailed structure.

Introduce a new class, `Paper`, which has the following attributes:

* `authors`, 
* `title`, 
* `a_id`,
* `year`, 
* `status` (published or in development), 
* `peer_rating` (Excellent, Good, Fair, Poor, Barely Acceptable, Unacceptable).

In [91]:
class Paper:
    def __init__(self, authors, title, a_id, status, year, peer_rating):
        allowed_status = ['published', 'in development']
        allowed_peer_rating = ['Excellent', 'Good', 'Fair', 'Barely Acceptable', 'Unacceptable']
        if status not in allowed_status:
            raise ValueError("Status is not right, please choose from the following: 'published', 'in development'")
        else:
            self.status = status
        if peer_rating not in allowed_peer_rating:
            raise ValueError("Peer rating is not right, please choose from the following: 'Excellent', 'Good', 'Fair', 'Barely Acceptable', 'Unacceptable'")
        else:
            self.peer_rating = peer_rating
        self.authors = authors
        self.title = title
        self.a_id = a_id
        self.year = year

    def __str__(self):
        if type(self.authors[0]) == str:
            return  f'{self.title}, {", ".join([author for author in self.authors])} et al. ({self.year}), a_id: '\
                    f'{self.a_id}, status: {self.status}, rating: {self.peer_rating}'
        else:
            return  f'{self.title}, {", ".join([str(author.title + " " + author.name + " " + author.surname) for author in self.authors])} et al. ({self.year}), a_id: '\
                    f'{self.a_id}, status: {self.status}, rating: {self.peer_rating}'

# Testing
authors = ['Ian Goodfellow', 'Yoshua Bengio', 'Aaron Courville']
paper1 = Paper(authors, 'Deep Learning', '1', 'published', 2016, 'Excellent')
print(paper1)

authors2 = ['Tomas Mikolov', 'Ilya Sutskever', 'Quoc Le']
paper2 = Paper(authors2, 'Sequence to Sequence Learning', '2', 'in development', 2014, 'Good')
print(paper2)

authors3 = ['John Doe', 'Jane Doe']
paper3 = Paper(authors3, 'Paper 3', '3', 'published', 2021, 'Excellent')
print(paper3)

Deep Learning, Ian Goodfellow, Yoshua Bengio, Aaron Courville et al. (2016), a_id: 1, status: published, rating: Excellent
Sequence to Sequence Learning, Tomas Mikolov, Ilya Sutskever, Quoc Le et al. (2014), a_id: 2, status: in development, rating: Good
Paper 3, John Doe, Jane Doe et al. (2021), a_id: 3, status: published, rating: Excellent


## Inheritence

In Object-Oriented programming, this concept enables us to transfer the methods and the properties of a class to another class.

### Task 3

Create a class named `Researcher`, which inherits the properties and methods from the `Person` class. Besides, this class has an additional parameter, `papers` which is `None` by default.

_Note:_ You should check if `papers` is `None` in `__init__` and set it to `[]` instead.

```python
class Researcher(Person):
    def __init__('Add arguments'):
        super().__init__(title, name, surname)
```

In [92]:
# Define your first researcher
# Expected output: Senior Researcher Tomas Mikolov

class Researcher(Person):
    def __init__(self, title, name, surname, papers=None):
        super().__init__(title, name, surname)
        if papers is None:
            self.papers = []

    def get_collab(self, researcher):
            collab_papers = []
            for paper in self.papers:
                for paper2 in researcher.papers:
                    if paper == paper2:
                        collab_papers.append(paper)
            return collab_papers

    def verify_co_authorship(self):
        for paper in self.papers:
            if len(paper.authors) > 1:
                return True
        return False
        

    def __str__(self):
        return super().__str__() + ' ' + str(self.papers)

    
    """
    Implement the `get_collab` function inside the `class Researcher` to discover the papers written by two researchers.
    """
    
# Testing
Test1 = Researcher('Senior Researcher', 'Tomas', 'Mikolov')
print(Test1)


Senior Researcher Tomas Mikolov []


### Task 4

Consider the following scientists:

1.  Paper _Deep Learning_ published by Yann LeCun, Yoshua Bengio, Geoffrey Hinton, in _nature 521_, id = https://doi.org/10.1038/nature14539, peer_rating = Excelent.

2. Paper _On the difficulty of training recurrent neural networks_ by Razvan Pascanu, Tomas Mikolov, Professor of computer science Yoshua Bengio, in ICML 2013, id = https://arxiv.org/abs/1211.5063, peer_rating = Excelent.

2. Paper _Generative Adversarial Nets_ by Ian Goodfellow and Yoshua Bengio, NeurIPS 2015, id = http://papers.nips.cc/paper/5423-generative-adversarial-nets.pdf, peer_rating = Excelent.

3. Paper _Handwritten Digit Recognition with a Back-Propagation Network_ by Computer Scientist Yann LeCun, NeurIPS 1989, id =  https://papers.nips.cc/paper/293-handwritten-digit-recognition-with-a-back-propagation-network, peer_rating = Excelent.

4. Paper _Gated Softmax Classification_ by Geoffrey Hintorn, NeurIPS 2010, id = http://papers.neurips.cc/paper/3895-gated-softmax-classification, peer_rating = Good.

_Note:_ Let us consider "Mr" as a default title for the researchers without a specific caption. Also, for the id of a paper, please use only integers from the provided links.

**a.** Define the next 5 scientists and use them in your `paper` objects.

**b.** Create the `verify_co_authorship` function inside the `class Researcher` which checks if a certain researcher ever co-authored a paper.
_Hint:_ Use `self.co_authored = False` inside the `__init__` function.

**c.** Implement the `get_collab` function inside the `class Researcher` to discover the papers written by two researchers.

For instance, if Yoshua Bengio is researcher2 and Ian Goodfellow is researcher3, then:

`print_papers(researcher2.get_collab(researcher3))` should output:

_Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), a_id: 5423, status: published, rating: Excelent_

_Note:_ This function helps you to print the papers from a given list.

```python
def print_papers(paper_list):
    for paper in paper_list:
        print(paper)
```

**d.** What are the papers written by Yoshua Bengio?

Expected output:

`Deep Learning, Computer Scientist Yann LeCun et al. (2015), a_id: 14539, status: published, rating: Excelent`

`Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), a_id: 5423, status: published, rating: Excelent`

`Paper On the difficulty of training recurrent neural networks, Mr Razvan Pascanu et al. (2013), a_id: 5063, status: published, rating: Excelent`

**e.** Did he ever co-author a paper?

**f.** Which papers are published by Yann LeCun?

Expected output:

`Deep Learning, Computer Scientist Yann LeCun et al. (2015), a_id: 14539, status: published, rating: Excelent`

`Handwritten Digit Recognition with a Back-Propagation Network, Computer Scientist Yann LeCun et al. (1989), a_id: 293, status: published, rating: Good`

In [93]:
def print_papers(paper_list):
    for paper in paper_list:
        print(paper)

Res1 = Researcher('Computer Scientist', 'Yann', 'LeCun')
Res2 = Researcher('Professor of CS', 'Yoshua', 'Bengio')
Res3 = Researcher('Mr', 'Geoffrey', 'Hinton')
Res4 = Researcher('Mr', 'Razvan', 'Pascanu')
Res5 = Researcher('Mr', 'Tomas', 'Mikolov')
Res6 = Researcher('Mr', 'Ian', 'Goodfellow')

ppr1 = Paper([Res1, Res2, Res3], 'Deep Learning', '14539', 'published', 2015, 'Excellent')
ppr2 = Paper([Res4, Res5, Res2], 'On the difficulty of training recurrent neural networks', '5063', 'published', 2012, 'Excellent')
ppr3 = Paper([Res6, Res2], 'Generative Adversarial Nets', '5423', 'published', 2015, 'Excellent')
ppr4 = Paper([Res1], 'Handwritten Digit Recognition with a Back-Propagation Network', '293', 'published', 1998, 'Excellent')
ppr5 = Paper([Res3], 'Gated Softmax Classification', '3895', 'published', 2010, 'Good')

Res1.papers = [ppr1, ppr4]
Res2.papers = [ppr1, ppr2, ppr3]
Res3.papers = [ppr1, ppr5]
Res4.papers = [ppr2]
Res5.papers = [ppr2]
Res6.papers = [ppr3]

print("Papers written by Yoshua Bengio and Ian Goodfellow:")
print_papers(Res2.get_collab(Res6))
print("\nPapers written by Yoshua Bengio:")
print_papers(Res2.papers)
print("\nDid Yoshua Bengio ever co-author a paper?")
print(Res2.verify_co_authorship())
print("\nPapers published by Yann LeCun:")
print_papers(Res1.papers)

Papers written by Yoshua Bengio and Ian Goodfellow:
Generative Adversarial Nets, Mr Ian Goodfellow, Professor of CS Yoshua Bengio et al. (2015), a_id: 5423, status: published, rating: Excellent

Papers written by Yoshua Bengio:
Deep Learning, Computer Scientist Yann LeCun, Professor of CS Yoshua Bengio, Mr Geoffrey Hinton et al. (2015), a_id: 14539, status: published, rating: Excellent
On the difficulty of training recurrent neural networks, Mr Razvan Pascanu, Mr Tomas Mikolov, Professor of CS Yoshua Bengio et al. (2012), a_id: 5063, status: published, rating: Excellent
Generative Adversarial Nets, Mr Ian Goodfellow, Professor of CS Yoshua Bengio et al. (2015), a_id: 5423, status: published, rating: Excellent

Did Yoshua Bengio ever co-author a paper?
True

Papers published by Yann LeCun:
Deep Learning, Computer Scientist Yann LeCun, Professor of CS Yoshua Bengio, Mr Geoffrey Hinton et al. (2015), a_id: 14539, status: published, rating: Excellent
Handwritten Digit Recognition with a Ba

### Task 5 

Consider an updated version of the `ScientificConference` class, which should have a modified version of the function `add_manuscript`.

Use the `status` and the `peer_rating` variables as a **threshold** to add papers in your `papers` dictionary. The conferences will only be accepting `Excelent` papers. For this case, the dictionary has the year of the paper as `key`, and the `values` are stored as a tuple of `(researcher, manuscript)`. For the papers which don't satisfy this condition, the message _"Please review your submission."_ is displayed.

For papers submitted in 2015, when printing the conference, the `str` function should output:

```
NeurIPS 2020: 
2015: 
Mr Ian Goodfellow: Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), id: 5423, status: published, rating: Excelent 
Computer Scientist Yann LeCun: Deep Learning, Computer Scientist Yann LeCun et al. (2015), id: 14539, status: published, rating: Excelent
```

In [94]:
class ScientificConferenceUpdate:
    """
    To define the properties of a class, 
    we use a special method called __init__.
    
    The special variable called "self"
    helps with associating the attributes
    w\ the new object: similar to `this`
    keyword from other programming languages
    and required to address variables from
    classes. 
    """
    def __init__(self, name):
        """
        Establish the attributes of the
        class and assign values to the 
        corresponding parameters.
        """ 
        self.name = name
        self.year = year
        """
        Add new attribute `papers`
        """
    
    def add_manuscript(self, manuscript, researcher):
        'TO DO'
        
    def __str__(self):
        """
        To return the String representation of
        an object, we use the __str__ method. 
        """
        result = self.name + ' ' + str(self.year) + ': \n'
        for year, papers in self.papers.items():
            result += f'{year}: \n'
            for (author, paper) in papers: 
                result += f'{author}: {paper} \n'
        return result